[package]
name = "parol-app"
edition.workspace = true

[[bin]]
name = "parol-app"
path = "app.rs"

[dependencies]
codespan-reporting = "0.12.0"
logos = "0.15.0"

[dev-dependencies]
lelwel = "0.7.1"
snapbox = "0.6.21"
