[package]
name = "parol-app"
edition.workspace = true

[[bin]]
name = "parol-app"
path = "app.rs"

[dependencies]
parol_runtime = "4.0.1"
scnr2 = "0.3.3"

[dev-dependencies]
parol = "4.1.1"
snapbox = "0.6.21"

[lints]
workspace = true
